#!/bin/bash

usage() {
  cat<<EOF


usage: $(basename $0) NAME [SERVICEACCOUNT] [OWNER]

Creates psp, role, rolebinding and (optionally) a service account
for a custom pod security policy

args:
  NAME           name to be used for psp, role and rolebinding (all three will be
                 prefixed with 'psp-' or 'psp:'
  SERVICEACCOUNT allow SERVICEACCOUNT to use this psp -- otherwise
                 a service account with name NAME will be created
  OWNER          if set, add an annotation with owner=OWNER to all resources

EOF
}

name=$1
test -n "${name:?"$(usage)"}"

sa=${2:-${name}}

owner=${3:+owner: ${3}}

if [ "${sa}" = "${name}" ]
then
cat<<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    ${owner}
  name: ${name}
EOF
fi

echo "---
# adjust the psp to your needs
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-${name}
  annotations:
    ${owner}
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  # requiredDropCapabilities:
  #   - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
  # Require the container to run without root privileges.
  #  rule: 'MustRunAsNonRoot'
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  # supplementalGroups:
  #   rule: 'MustRunAs'
  #   ranges:
  #     # Forbid adding the root group.
  #     - min: 1
  #       max: 65535
  # fsGroup:
  #   rule: 'MustRunAs'
  #   ranges:
  #     # Forbid adding the root group.
  #     - min: 1
  #       max: 65535
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    ${owner}
  name: psp:${name}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-${name}
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    ${owner}
  name: psp:${name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:${name}
subjects:
  - kind: ServiceAccount
    name: ${sa}

# uncomment to grant access to psp to every service account
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: system:serviceaccounts

# uncomment to grant access to psp to every authenticated user
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: system:authenticated

"
